name: pw_dev_backend
description: Backend server for pw_dev frontend integration.
version: 1.0.0
environment:
  sdk: ^3.11.1

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shelf_web_socket: ^2.0.1
  web_socket_channel: ^3.0.2
